In [1]:
KEPLER_PATH = "datasets/kepler"
import pandas as pd
def load_housing_data(housing_path=KEPLER_PATH):
    csv_path = os.path.join(housing_path, "ExoTrain.csv")
    return pd.read_csv(csv_path)

In [4]:
import os
kepler = load_housing_data()

In [5]:
kepler.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3960 entries, 0 to 3959
Columns: 3198 entries, LABEL to FLUX.3197
dtypes: float64(3197), int64(1)
memory usage: 96.6 MB

In [7]:
kepler.describe()

,LABEL,FLUX.1,FLUX.2,FLUX.3,FLUX.4,FLUX.5,FLUX.6,FLUX.7,FLUX.8,FLUX.9,...,FLUX.3188,FLUX.3189,FLUX.3190,FLUX.3191,FLUX.3192,FLUX.3193,FLUX.3194,FLUX.3195,FLUX.3196,FLUX.3197
count,3960.000000,3960.000000,3960.000000,3960.000000,3960.000000,3960.000000,3960.000000,3960.000000,3960.000000,3960.000000,...,3.960000e+03,3.960000e+03,3.960000e+03,3.960000e+03,3.960000e+03,3.960000e+03,3960.000000,3960.000000,3960.000000,3960.000000
mean,1.008333,-95.957018,-63.100912,-89.827429,-85.076212,-131.238222,-128.423841,-161.990629,-108.328247,-110.952179,...,4.498606e+02,5.627187e+02,6.292302e+02,6.744195e+02,5.985866e+02,5.929736e+02,-446.876126,-459.238937,-375.863836,-326.801631
std,0.090917,5379.590354,5124.130820,5007.125786,5315.021226,5817.851500,6704.807347,7174.806624,6537.286380,5647.280531,...,3.075134e+04,3.900914e+04,4.813277e+04,5.509827e+04,5.605247e+04,5.852504e+04,16136.183166,16922.160791,16198.959474,14734.937312
min,1.000000,-216192.000000,-219338.000000,-212822.000000,-217468.000000,-221268.000000,-292749.390000,-338450.030000,-289405.780000,-223916.000000,...,-3.240480e+05,-3.045540e+05,-2.933140e+05,-2.838420e+05,-3.288214e+05,-4.788706e+05,-775322.000000,-732006.000000,-700992.000000,-643170.000000
25%,1.000000,-40.877500,-38.012500,-37.037500,-34.595000,-31.632500,-32.780000,-28.205000,-27.625000,-27.212500,...,-1.745250e+01,-1.958750e+01,-1.775500e+01,-2.022750e+01,-2.229750e+01,-2.450000e+01,-25.075000,-24.392500,-22.072500,-20.427500
50%,1.000000,-0.605000,-1.035000,-1.000000,-0.690000,-1.150000,-1.450000,-1.365000,-1.265000,-0.885000,...,2.130000e+00,2.550000e+00,3.135000e+00,3.520000e+00,3.280000e+00,3.685000e+00,-1.110000,0.010000,0.145000,0.950000
75%,1.000000,50.275000,45.227500,44.782500,41.317500,39.970000,34.842500,33.820000,31.250000,30.022500,...,2.113250e+01,2.116000e+01,2.530750e+01,2.870500e+01,2.698500e+01,3.052500e+01,18.795000,18.752500,19.822500,19.645000
max,2.000000,150725.800000,129578.360000,102184.980000,82253.980000,76050.000000,77224.000000,78456.000000,79075.000000,80056.000000,...,1.779338e+06,2.379227e+06,2.992070e+06,3.434973e+06,3.481220e+06,3.616292e+06,201974.000000,204761.000000,207590.000000,211302.000000

In [10]:
target = kepler["LABEL"]

In [11]:
data = kepler[1:]

In [12]:
data.describe()

,LABEL,FLUX.1,FLUX.2,FLUX.3,FLUX.4,FLUX.5,FLUX.6,FLUX.7,FLUX.8,FLUX.9,...,FLUX.3188,FLUX.3189,FLUX.3190,FLUX.3191,FLUX.3192,FLUX.3193,FLUX.3194,FLUX.3195,FLUX.3196,FLUX.3197
count,3959.000000,3959.000000,3959.000000,3959.000000,3959.000000,3959.000000,3959.000000,3959.000000,3959.000000,3959.000000,...,3.959000e+03,3.959000e+03,3.959000e+03,3.959000e+03,3.959000e+03,3.959000e+03,3959.000000,3959.000000,3959.000000,3959.000000
mean,1.008083,-95.971435,-63.108305,-89.835332,-85.087575,-131.251339,-128.437888,-162.009684,-108.334057,-110.958995,...,4.499750e+02,5.628690e+02,6.293973e+02,6.745962e+02,5.987391e+02,5.931232e+02,-446.986047,-459.356567,-375.962816,-326.889212
std,0.089552,5380.269819,5124.778071,5007.758254,5315.692563,5818.586343,6705.654230,7175.712834,6538.112150,5647.993871,...,3.075522e+04,3.901407e+04,4.813885e+04,5.510523e+04,5.605955e+04,5.853243e+04,16138.219981,16924.296753,16201.004504,14736.797575
min,1.000000,-216192.000000,-219338.000000,-212822.000000,-217468.000000,-221268.000000,-292749.390000,-338450.030000,-289405.780000,-223916.000000,...,-3.240480e+05,-3.045540e+05,-2.933140e+05,-2.838420e+05,-3.288214e+05,-4.788706e+05,-775322.000000,-732006.000000,-700992.000000,-643170.000000
25%,1.000000,-40.885000,-38.055000,-36.980000,-34.550000,-31.495000,-32.685000,-28.125000,-27.610000,-27.190000,...,-1.746500e+01,-1.952500e+01,-1.771000e+01,-2.020000e+01,-2.230500e+01,-2.450000e+01,-25.080000,-24.415000,-22.095000,-20.435000
50%,1.000000,-0.600000,-1.030000,-1.000000,-0.660000,-1.150000,-1.450000,-1.360000,-1.260000,-0.880000,...,2.130000e+00,2.550000e+00,3.140000e+00,3.530000e+00,3.280000e+00,3.690000e+00,-1.100000,0.010000,0.140000,0.950000
75%,1.000000,50.330000,45.235000,44.845000,41.345000,39.980000,34.875000,33.860000,31.250000,30.035000,...,2.113500e+01,2.119000e+01,2.532500e+01,2.873000e+01,2.699000e+01,3.053000e+01,18.800000,18.755000,19.835000,19.615000
max,2.000000,150725.800000,129578.360000,102184.980000,82253.980000,76050.000000,77224.000000,78456.000000,79075.000000,80056.000000,...,1.779338e+06,2.379227e+06,2.992070e+06,3.434973e+06,3.481220e+06,3.616292e+06,201974.000000,204761.000000,207590.000000,211302.000000

In [13]:
target.describe()

count    3960.000000
mean        1.008333
std         0.090917
min         1.000000
25%         1.000000
50%         1.000000
75%         1.000000
max         2.000000
Name: LABEL, dtype: float64